samsung: sec_debug_base: Fix build when SCHED_INFO is disabled
../drivers/samsung/debug/sec_debug_base.c:264:37: error: no member named 'pcount' in 'struct sched_info'
  263 |         SET_MEMBER_TYPE_INFO(&secdbg_sdn_va->task.ts.sched_info__pcount,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  264 |                                         struct task_struct, sched_info.pcount);
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
../drivers/samsung/debug/sec_debug_internal.h:266:37: note: expanded from macro 'SET_MEMBER_TYPE_INFO'
  266 |                 (PTR)->size = sizeof(((TYPE *)0)->MEMBER); \
      |                                      ~~~~~~~~~~~~~^~~~~~
../drivers/samsung/debug/sec_debug_base.c:263:2: error: no member named 'pcount' in 'sched_info'
  263 |         SET_MEMBER_TYPE_INFO(&secdbg_sdn_va->task.ts.sched_info__pcount,
      |         ^
  264 |                                         struct task_struct, sched_info.pcount);
      |                                                                       ~~~~~~~
../drivers/samsung/debug/sec_debug_internal.h:267:19: note: expanded from macro 'SET_MEMBER_TYPE_INFO'
  267 |                 (PTR)->offset = offsetof(TYPE, MEMBER); \
      |                                 ^              ~~~~~~
../include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
   17 | #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
      |                                 ^                         ~~~~~~
./../include/linux/compiler_types.h:133:35: note: expanded from macro '__compiler_offsetof'
  133 | #define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
      |                                         ^                     ~
../drivers/samsung/debug/sec_debug_base.c:267:17: error: no member named 'run_delay' in 'struct sched_info'
  265 |         SET_MEMBER_TYPE_INFO(&secdbg_sdn_va->task.ts.sched_info__run_delay,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  266 |                                         struct task_struct,
      |                                         ~~~~~~~~~~~~~~~~~~~
  267 |                                         sched_info.run_delay);
      |                                         ~~~~~~~~~~~^~~~~~~~~~
../drivers/samsung/debug/sec_debug_internal.h:266:37: note: expanded from macro 'SET_MEMBER_TYPE_INFO'
  266 |                 (PTR)->size = sizeof(((TYPE *)0)->MEMBER); \
      |                                      ~~~~~~~~~~~~~^~~~~~
../drivers/samsung/debug/sec_debug_base.c:265:2: error: no member named 'run_delay' in 'sched_info'
  265 |         SET_MEMBER_TYPE_INFO(&secdbg_sdn_va->task.ts.sched_info__run_delay,
      |         ^
  266 |                                         struct task_struct,
  267 |                                         sched_info.run_delay);
      |                                                   ~~~~~~~~~~
../drivers/samsung/debug/sec_debug_internal.h:267:19: note: expanded from macro 'SET_MEMBER_TYPE_INFO'
  267 |                 (PTR)->offset = offsetof(TYPE, MEMBER); \
      |                                 ^              ~~~~~~
../include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
   17 | #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
      |                                 ^                         ~~~~~~
./../include/linux/compiler_types.h:133:35: note: expanded from macro '__compiler_offsetof'
  133 | #define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
      |                                         ^                     ~
../drivers/samsung/debug/sec_debug_base.c:270:17: error: no member named 'last_arrival' in 'struct sched_info'
  268 |         SET_MEMBER_TYPE_INFO(&secdbg_sdn_va->task.ts.sched_info__last_arrival,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  269 |                                         struct task_struct,
      |                                         ~~~~~~~~~~~~~~~~~~~
  270 |                                         sched_info.last_arrival);
      |                                         ~~~~~~~~~~~^~~~~~~~~~~~~
../drivers/samsung/debug/sec_debug_internal.h:266:37: note: expanded from macro 'SET_MEMBER_TYPE_INFO'
  266 |                 (PTR)->size = sizeof(((TYPE *)0)->MEMBER); \
      |                                      ~~~~~~~~~~~~~^~~~~~
../drivers/samsung/debug/sec_debug_base.c:268:2: error: no member named 'last_arrival' in 'sched_info'
  268 |         SET_MEMBER_TYPE_INFO(&secdbg_sdn_va->task.ts.sched_info__last_arrival,
      |         ^
  269 |                                         struct task_struct,
  270 |                                         sched_info.last_arrival);
      |                                                   ~~~~~~~~~~~~~
../drivers/samsung/debug/sec_debug_internal.h:267:19: note: expanded from macro 'SET_MEMBER_TYPE_INFO'
  267 |                 (PTR)->offset = offsetof(TYPE, MEMBER); \
      |                                 ^              ~~~~~~
../include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
   17 | #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
      |                                 ^                         ~~~~~~
./../include/linux/compiler_types.h:133:35: note: expanded from macro '__compiler_offsetof'
  133 | #define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
      |                                         ^                     ~
../drivers/samsung/debug/sec_debug_base.c:273:17: error: no member named 'last_queued' in 'struct sched_info'
  271 |         SET_MEMBER_TYPE_INFO(&secdbg_sdn_va->task.ts.sched_info__last_queued,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  272 |                                         struct task_struct,
      |                                         ~~~~~~~~~~~~~~~~~~~
  273 |                                         sched_info.last_queued);
      |                                         ~~~~~~~~~~~^~~~~~~~~~~~
../drivers/samsung/debug/sec_debug_internal.h:266:37: note: expanded from macro 'SET_MEMBER_TYPE_INFO'
  266 |                 (PTR)->size = sizeof(((TYPE *)0)->MEMBER); \
      |                                      ~~~~~~~~~~~~~^~~~~~
../drivers/samsung/debug/sec_debug_base.c:271:2: error: no member named 'last_queued' in 'sched_info'
  271 |         SET_MEMBER_TYPE_INFO(&secdbg_sdn_va->task.ts.sched_info__last_queued,
      |         ^
  272 |                                         struct task_struct,
  273 |                                         sched_info.last_queued);
      |                                                   ~~~~~~~~~~~~
../drivers/samsung/debug/sec_debug_internal.h:267:19: note: expanded from macro 'SET_MEMBER_TYPE_INFO'
  267 |                 (PTR)->offset = offsetof(TYPE, MEMBER); \
      |                                 ^              ~~~~~~
../include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
   17 | #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
      |                                 ^                         ~~~~~~
./../include/linux/compiler_types.h:133:35: note: expanded from macro '__compiler_offsetof'
  133 | #define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
      |                                         ^                     ~
8 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
(cherry picked from commit 900b615f19b5450d53cd24ecfb82cfe906c68404)
Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>